name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE: "true"
          SHOW_TOTAL_CODE_TIME: "false"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_COMMIT: "true"
          SYMBOL_VERSION: 2
          SHOW_SHORT_INFO: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_EDITORS: "false"
          SHOW_LOC_CHART: "false"
          
